name: quizapp
description: A new Flutter application for answering quizes.
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fluttertoast: ^4.0.1
  font_awesome_flutter: ^8.8.1
  firebase_core: ^0.4.4+3
  image_picker: ^0.6.4
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  firebase_storage: ^3.1.5
  path: ^1.6.4
  google_sign_in: ^4.3.0
  shared_preferences: ^0.5.6+3
  carousel_slider: ^1.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/