name: quizapp
description: A new Flutter application for answering quizes.
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.5
  fluttertoast: ^8.1.1
  font_awesome_flutter: ^10.2.1
  firebase_core: ^24.1.1
  image_picker: ^0.8.6
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.3
  path: ^1.8.2
  google_sign_in: ^5.4.2
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/